# Generated by Django 3.1 on 2023-03-22 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_categrory',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
