# Generated by Django 3.1 on 2023-03-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230322_1748'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variation',
            field=models.ManyToManyField(blank=True, null=True, to='store.Variation'),
        ),
    ]
