# Generated by Django 3.1 on 2023-03-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230322_1748'),
        ('carts', '0002_cartitems_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
